---
- hosts: all
  gather_facts: yes
  become: yes

  vars:
    packer_box_description: "Built With Packer!"
    packer_box_version: "0.0.0"

  tasks:

    - name: Create Version File
      copy:
        content: "Box Description: {{ packer_box_description }}\nBox Version: v{{ packer_box_version }}\n"
        dest: /root/.packer_info

    - name: Install EPEL
      dnf:
        name: "epel-release"
        state: latest

    - name: Upgrade All Packages
      dnf:
        name: "*"
        state: latest

    - name: Autoremove Unneeded Packages Installed As Dependencies
      dnf:
        autoremove: yes

    - name: Remove iwl-* Packages
      dnf:
        name: "iwl-*"
        state: absent
        autoremove: yes
      ignore_errors: yes

    - name: Install Useful Packages
      dnf:
        name:
          - vim
          - tmux
          - curl
          - wget
          - git
          - rsync
          - tcpdump
          - net-tools
          - bind-utils
          - nfs-utils
          - python3
          - python3-libselinux

    - name: Configure SSHD
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        state: present
      with_items:
        - { regexp: '^UseDNS', line: 'UseDNS no' }
        - { regexp: '^GSSAPIAuthentication', line: 'GSSAPIAuthentication no' }

    - name: Create A .ssh Directory for the vagrant User
      file:
        path: /home/vagrant/.ssh
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0700

    - name: Insert The Vagrant Public SSH Key
      get_url:
        url: https://raw.githubusercontent.com/hashicorp/vagrant/master/keys/vagrant.pub
        dest: /home/vagrant/.ssh/authorized_keys
        owner: vagrant
        group: vagrant
        mode: 0600

    - name: Get The Current Kernel Release
      command: uname -r
      changed_when: no
      register: kernel_release

    - name: Install Dependencies For VirtualBox Guest Additions
      dnf:
        name:
          - bzip2
          - dkms
          - kernel-headers
          - kernel-devel
          - "kernel-devel-{{ kernel_release.stdout }}"
          - gcc
          - cpp
          - make
          - perl
      when: ansible_virtualization_type == "virtualbox"

    - name: Get VirtualBox Version
      command: cat /home/vagrant/.vbox_version
      changed_when: no
      register: virtualbox_version
      when: ansible_virtualization_type == "virtualbox"

    - name: Mount VirtualBox Guest Additions ISO
      mount:
        name: /tmp/vbox
        src: "/home/vagrant/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso"
        opts: loop
        state: mounted
        fstype: iso9660
      when: ansible_virtualization_type == "virtualbox"

    - name: Run VirtualBox Guest Additions Installer
      command: sh /tmp/vbox/VBoxLinuxAdditions.run
      changed_when: yes
      when: ansible_virtualization_type == "virtualbox"

    - name: Unmount VirtualBox Guest Additions ISO
      mount:
        name: /tmp/vbox
        src: "/home/vagrant/VBoxGuestAdditions_{{ virtualbox_version.stdout }}.iso"
        state: absent
        fstype: iso9660
      when: ansible_virtualization_type == "virtualbox"

    - name: Remove Unneeded Packages
      dnf:
        name:
          - cpp
          - kernel-headers
          - "kernel-devel*"
        state: absent

    - name: Enable Firewalld
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Firewalld Enable ssh
      firewalld:
        zone: public
        service: ssh
        permanent: yes
        state: enabled

    - name: Firewalld Disable cockpit
      firewalld:
        zone: public
        service: cockpit
        permanent: yes
        state: disabled

    - name: Firewalld Disable dhcpv6-client
      firewalld:
        zone: public
        service: cockpit
        permanent: yes
        state: disabled

    - name: Firewalld Set Default Zone Public
      command: firewall-cmd --set-default-zone=public

    - name: Firewalld Reload
      command: firewall-cmd --reload
